== Conformance
_(Mandatory for standards)_

=== Conformance classes

This document establishes 1 conformance class:

- DGIWG basic WPS.


DGIWG WPS Profile conformance classes define requirements for WPS 2.0 servers allowing distribution of geographic data in a military environment.
Annex A lists the conformance abstract tests which shall be exercised on any software
artefact claiming to implement the DGIWG WPS profile.

[#conf,reftext='{table-caption} {counter:table-num}']
[cols="4",options="header"]
.Conformance classes
!===
|Conformance class name |Operation or behavior | OGC WPS Conformance Test | DGIWG WPS Conformance Test
|DGIWG basic WPS http://www.dgiwg.org/std/wps/1.0/conf/basic | DGIWG requirements x to y | - | Annex A.1
!===

NOTE: "http://www.dgiwg.org/std/wps/1.0/conf/basic" is an HTTP-URI which works as an identifier for the DGIWG basic conformance class. It is not an URL, redirecting to a web page. 1.0 identifies the version of the DGIWG standard (not the version of WPS it profiles).

=== Backward compatibility
