= Parameters for Geocoding process - _Draft_

Some more info here https://geoservices.ign.fr/documentation/geoservices/geocodage.html

Implemented as an OGC OpenLS service

Provides coordinates from
 * POI /Place names
 * adress
 * cadastral parcel
== _by POI_
*request*

countryCode = PositionOfInterest
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<XLS
  xmlns:xls="http://www.opengis.net/xls"
  xmlns:gml="http://www.opengis.net/gml"
  xmlns="http://www.opengis.net/xls"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  version="1.2"
  xsi:schemaLocation="http://www.opengis.net/xls http://schemas.opengis.net/ols/1.2/olsAll.xsd">
    <RequestHeader/>
    <Request requestID="1" version="1.2" methodName="LocationUtilityService">
       <GeocodeRequest returnFreeForm="false">
         <Address countryCode="PositionOfInterest">
                <freeFormAddress>rennes</freeFormAddress>
         </Address>
       </GeocodeRequest>
    </Request>
</XLS>
----
<1> Sample POI request.

*response*

 * Point (location found)
 * GeocodeMatchCode (phonetic and orthographic proximity of the name from 0 to 1)

== _by administrative unit_

*request*

countryCode = Administratif
[source,xml]
----
 <Request requestID="1" version="1.2" methodName="LocationUtilityService">
   <GeocodeRequest returnFreeForm="false">
     <Address countryCode="Administratif">
       <freeFormAddress>Bretagne</freeFormAddress>
     </Address>
   </GeocodeRequest>
 </Request>
----
<2> Sample by Admin Unit request.

*response*

* Point (location found) of the admin unit (Capital city)
* Adress of the Admin Unit and oher information

== _by adress_
*request*

countryCode="StreetAddress
[source,xml]
----
 <RequestHeader srsName="epsg:4326"/>
   <Request maximumResponses="25" methodName="GeocodeRequest" requestID="uid42" version="1.2">
   <GeocodeRequest returnFreeForm="false">
     <Address countryCode="StreetAddress">
       <freeFormAddress>2 avenue Pasteur 94160 Saint-Mandé</freeFormAddress>
     </Address>
   </GeocodeRequest>
   </Request>
----
<3> Sample non structured adress request

returnFreeForm for structured adress back

*response*

* Point (location found) of the admin unit (Capital city)
* Adress / Street / Municipality
* quality of geocoding

*request*
[source,xml]
----
<RequestHeader/>
    <Request requestID="1" version="1.2" methodName="LocationUtilityService">
       <GeocodeRequest returnFreeForm="false">
           <Address countryCode="StreetAddress">
               <StreetAddress>
                        <Street>1 rue Marconi</Street>
               </StreetAddress>
               <Place type="Municipality">Metz</Place>
               <PostalCode>57000</PostalCode>
           </Address>
       </GeocodeRequest>
    </Request>
----
<4> Sample structured adress request

== _other filter criteria_
spatial filter with BBox
[source,xml]
----
<GeocodeRequest returnFreeForm="false">
  <Address countryCode="PositionOfInterest">
    <freeFormAddress>Saint-Mandé</freeFormAddress>
    <gml:envelope>
      <gml:pos>48.80 2.35</gml:pos>
      <gml:pos>48.86 2.47</gml:pos>
    </gml:envelope>
  </Address>
</GeocodeRequest>
----

== _by casdastral parcel_
semnatic filter
[source,xml]
----
<GeocodeRequest returnFreeForm="false">
  <Address countryCode="PositionOfInterest">
    <freeFormAddress>Saint-Mandé</freeFormAddress>
    <Place type="Departement">41</Place>
  </Address>
</GeocodeRequest>
----
