== Conformance
_(Mandatory for standards)_

=== Conformance classes

This document establishes xx conformance classe(s):

- DGIWG process,
- DGIWG generic xxx process profile,
- #...#

_"DGIWG process"_ class define requirements for defining generic process description
_"DGIWG generic xxx process profile"_ classes defines generic process profiles according to "DGIWG process" conformance class. Process profiles are blueprints for process implementations and are meant to harmonize process implementations to a certain degree. They serve as a reference for process implementations by providing a description of what the process actually does. These generic processes profiles can be implemented by OGC WPS standards (verions 1 or 2) or possibliby other geoprocessing APIs.
Annex A lists the conformance abstract tests which shall be exercised on process profiles claiming to implement these conformance classes.

[#conf,reftext='{table-caption} {counter:table-num}']
[cols="4",options="header"]
.Conformance classes
!===
|Conformance class name |Operation or behavior | OGC WPS Conformance Test | DGIWG WPS Conformance Test
|DGIWG process  http://www.dgiwg.org/std/geoprocessing/1.0/conf/process | DGIWG requirement y to z | - | Annex A.1
|DGIWG generic measurement process profile  http://www.dgiwg.org/std/geoprocessing/1.0/conf/generic-measurement | DGIWG requirement y to z | - | Annex A.2.1
|DGIWG generic elevation process profile http://www.dgiwg.org/std/geoprocessing/1.0/conf/generic-elevation | DGIWG requirement y to z | - | Annex A.2.2
|#DGIWG generic xxxx process profile http://www.dgiwg.org/std/geoprocessing/1.0/conf/generic-xxxx#| DGIWG requirement y to z | - | Annex A.2.3
!===


=== Backward compatibility
