:bibtex-file: ../resources/bibtex-file.bib
:bibtex-style: ../resources/lncs.csl

==== Generic process: Distance measurement

	  Identifier	http://www.dgiwg.org/service/processing/process/distancemeasurement
	  Title	Distance measurement
	  Keywords	distance
	  Abstract	It provides the distance between two or more points.
	  Metadata

===== Input: List of points

	  Identifier	points_list
	  Title	List of points
	  Keywords
	  Abstract	List of two or more points in a given CRS. CRS may be 2D or 3D (with Z or height information).
	  Metadata
	  Multiplicity	1

===== Input: Method of measurement

	  Identifier	measurement_method
	  Title	Method of measurement
	  Keywords
	  Abstract	Method of measurement to be used for the calculation (for example euclidean, geodesic, …). This could include Z coordinate (or height above elispoid).
	  Metadata
	  Multiplicity	0..1

===== Input: Unit of measure

	  Identifier	uom
	  Title	Unit of measure
	  Keywords
	  Abstract	Unit of measure for the measured distance(s) to be returned.
	  Metadata
	  Multiplicity	1

===== Output: Distance results

	  Identifier	distance_results
	  Title	Distance results
	  Keywords
	  Abstract	Result set containing individual distance between each point pair and/or the sum. This should include uom.
	  Metadata
