:bibtex-file: ../resources/bibtex-file.bib
:bibtex-style: ../resources/lncs.csl

==== Generic process : Geopackage creation

	  Identifier	http://www.dgiwg.org/service/processing/process/geopackage
	  Title	Geopackage creation
	  Keywords	Geopackage, vector, raster, imagery, coverage
	  Abstract	It provides geopackage file from input data.
	  Metadata

===== Input: Area of interest

	  Identifier	aoi
	  Title	Area of interest
	  Keywords
	  Abstract	Area of interest where a process will be executed. This could be a BBOX, a polygon, or any surface geometry.. (GM_Surface)
	  Metadata
	  Multiplicity	1

===== Input: Geopackage name

	  Identifier	name
	  Title	Geopackage name
	  Keywords
	  Abstract	Name of the generated geopackage
	  Metadata
	  Multiplicity	1

===== Input: Geopackage description

	  Identifier	description
	  Title	Geopackage description
	  Keywords
	  Abstract	Description of the generated geopackage
	  Metadata
	  Multiplicity	0..1

===== Input: Data sources

	  Identifier	data_sources
	  Title	Data sources
	  Keywords	tiles, chart maps, imagery, vector, elevation
	  Abstract	Selection of input data to compute the geopackage file. A same source can contain different layers; desired layers to be package shall be specified in the request.
	  Metadata
	  Multiplicity	1..n

===== Output: Geopackage file

    	  Identifier	geopackage
    	  Title	Geopackage file
    	  Keywords	gpkg
    	  Abstract	Generated geopackage file according to input data and provided parameters.
    	  Metadata
