:bibtex-file: ../resources/bibtex-file.bib
:bibtex-style: ../resources/lncs.csl

==== Generic process : Helicopter landing zone

	  Identifier	http://www.dgiwg.org/service/processing/process/hlz
	  Title	Helicopter landing zone
	  Keywords	helicopter, landing zone, slope, obstacle
	  Abstract	Helicopter landing zones contain one or more helicopter landing sites.
	  Metadata

===== Input: 	Elevation data

	  Identifier	elevation_data
	  Title	Elevation data
	  Keywords	elevation, height, Digital Surface Model, Digital Elevation Model
	  Abstract	Digital representation of the earth's surface. Elevation data on which the process will be executed. It may be internal data (with a choice for the users) or data provided by the user itself (URI, external service, …).
	  Metadata
	  Multiplicity	0..1

===== Input: Land cover

	  Identifier	land_cover
	  Title	Land cover
	  Keywords	land, cover, vegetation, water, brush;
	  Abstract	General land cover and vegetation types over areas of land, including water.
	  Metadata
	  Multiplicity	0..1

===== Input: Maximum slope tolerance

	  Identifier	max_slope_tolerance
	  Title	Maximum slope tolerance
	  Keywords	slope, units
	  Abstract	The maximum slope tolerance with units (degrees or percentage).
	  Metadata
	  Multiplicity	1

===== Input: Minimum radius

	  Identifier	min_radius
	  Title	Minimum radius
	  Keywords	radius
	  Abstract	The minimum necessary radius of landing zone, based on aircraft used.  See aircraft specs or operational guidance.
	  Metadata
	  Multiplicity	1

===== Input: Surface obstructions height tolerance

	  Identifier	height_tolerance
	  Title	Surface obstructions height tolerance
	  Keywords	z value, obstacle
	  Abstract	Maximum size object suitable in HLZ with UOM ; ground clearance of aircraft.
	  Metadata
	  Multiplicity	1

===== Output: HLZ analysis results

	  Identifier	hlz_results
	  Title	HLZ analysis results
	  Keywords
	  Abstract	A coverage depicting zones large enough for a helicopter to land and take off.
	  Metadata
